### ISSUE TITLE
Not updating once page is loaded

### ISSUE THREAD

**Issue by manikantag** [mrzepinski/angular-debug-bar#1]
Hi, the idea is very good. But, it seems the stats (esp., num. of watchers) are not refreshing once the page is loaded. For ex: when new elements are inserted using `ng-if` or `ng-repeat`. Is there any setting to calculate the num of watchers in every $digest? Thanks.

**Comment by mrzepinski** [comment]
@manikantag I updated and refactored some code: https://github.com/mrzepinski/angular-debug-bar/commit/ce9f98171e4217764b4eccca7e2594118620f11c

`v0.3.0` is now released. Let me know if it works for you right now :)

Thanks for your feedback!

**Comment by manikantag** [comment]
Yeah, seems working now. Thanks.
