### ISSUE TITLE
Readme needs example or screenshot

### ISSUE THREAD

**Issue by Martinspire** [mrzepinski/angular-debug-bar#3]
Nice to see a debug bar, but i think i speak for many if i say that i'd like to see one before i implement it. Either by screenshot or by demo-page

**Comment by mrzepinski** [comment]
@Martinspire Demo is here: http://mrzepinski.github.io/angular-debug-bar/

Look at the right bottom corner and blue button.

**Comment by Martinspire** [comment]
Thanks for adding and adding a screen to the readme ;)
