### ISSUE TITLE
Provide support for choosing a subset of the default plugins

### ISSUE THREAD

**Issue by anaynayak** [mrzepinski/angular-debug-bar#4]
Thanks for building angular-debug-bar. I can see that the application currently provides support for clearing all the default plugins. Is it possible to enhance it to only retain a subset of the plugins ? 

```
.config(['debugBarProvider', function (debugBarProvider) {
  debugBarProvider.clearDefaultPlugins(['cssFilesCount', 'jsFilesCount', ...]);
}]);
```

For our application, this will let us focus on the ones that we care about the most.

**Comment by anaynayak** [comment]
I can send a PR if the changes done in https://github.com/anaynayak/angular-debug-bar/commit/6b8c1306d0630e3626b54a5e2e96bbbd395c68b0 look alright

**Comment by mrzepinski** [comment]
@anaynayak Thanks for your feedback. It's ok and you can send your PR. I'll merge that and new version will be available then.

**Comment by mrzepinski** [comment]
@anaynayak `1.1.0` is available ;)

**Comment by anaynayak** [comment]
Awesome! Thanks @mrzepinski
